# Generated by Django 3.1.6 on 2021-02-07 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Deportista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('lugar_nacimiento', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('peso', models.FloatField()),
                ('estatura', models.FloatField()),
                ('entrenador', models.CharField(max_length=100)),
                ('foto', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('Correo', models.CharField(max_length=200)),
                ('es_admin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('video', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('resultado', models.FloatField()),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olimpicos.deporte')),
                ('deportista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olimpicos.deportista')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olimpicos.evento')),
            ],
        ),
        migrations.AddField(
            model_name='deporte',
            name='modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olimpicos.modalidad'),
        ),
    ]
