# Generated by Django 3.1.6 on 2021-02-08 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olimpicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=500)),
                ('fecha', models.TimeField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olimpicos.estudiante')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olimpicos.evento')),
            ],
        ),
    ]
