# Generated by Django 3.1.6 on 2021-02-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimpicos', '0003_auto_20210213_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deportista',
            name='foto',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
